
version: '3'
services:
  consumer:
    container_name: consumer
    build:
      context: .
    networks:
      - rabbitmq-net
    volumes:
      - ./:/usr/src/app
    depends_on:
      - rabbit

  producer:
    container_name: producer
    build:
      context: .
    networks:
      - rabbitmq-net
    volumes:
      - ./:/usr/src/app
    depends_on:
      - rabbit

  rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbitmq-net    


networks:
  rabbitmq-net:
    driver: bridge